ARQSI/Lugares_Cancela_Visita/ARQSI_Projeto/Lugares/Controllers/POIsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DataAccessLibrary.DAL;
using DataAccessLibrary.Models;
using Microsoft.AspNet.Identity;
using System.Diagnostics;
using DataAccessLibrary.Infrastructure;

namespace NewNewLugares.Controllers
{
    [Authorize(Roles = "Administrador, Utilizador")]
    public class POIsController : Controller
    {
        private DatumDbContext db = new DatumDbContext();

        // GET: POIs
        [AllowAnonymous]
        public ActionResult Index()
        {
            var pOIs = db.POIs.Include(p => p.Local).Include(p => p.User).Include(p => p.Hashtags);
            List<POI> validated = new List<POI>();
            foreach(POI poi in pOIs)
            {
                if(poi.Validated)
                {   
                    validated.Add(poi);
                }
            }
            return View(validated);
        }

        // GET: POIs/Details/5
        [Authorize(Roles = "Administrador")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            POI pOI = db.POIs.Find(id);
            if (pOI == null)
            {
                return HttpNotFound();
            }
            return View(pOI);
        }

        // GET: POIs/Create
        [Authorize(Roles = "Administrador, Utilizador")]
        public ActionResult Create()
        {
            ViewBag.LocalID = new SelectList(db.Locals, "LocalID", "Name");
            ViewBag.UserId = new SelectList(db.Users, "Id", "Email");
            return View();
        }

        // POST: POIs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrador, Utilizador")]
        public ActionResult Create([Bind(Include = "POIID,Name,Description,LocalID,UserId,Validated")] POI pOI, string hashTags)
        {
            pOI.UserId = User.Identity.GetUserId();
            if(User.IsInRole("Administrador"))
            {
                pOI.Validated = true;
            }
            if (User.IsInRole("Utilizador"))
            {
                String[] htags = hashTags.Split(',');
                foreach(string hashTg in htags)
                {
                    Hashtag h = new Hashtag();
                    h.Descricao = hashTg;
                    db.Hashtags.Add(h);
                    
                }
            }
            if (ModelState.IsValid)
            {
                db.POIs.Add(pOI);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.LocalID = new SelectList(db.Locals, "LocalID", "Name", pOI.LocalID);
            ViewBag.UserId = new SelectList(db.Users, "Id", "Email", pOI.UserId);
            return View(pOI);
        }

        // GET: POIs/Edit/5
        [Authorize(Roles = "Administrador")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            POI pOI = db.POIs.Find(id);
            if (pOI == null)
            {
                return HttpNotFound();
            }

            if (pOI.CheckNotOwner(User.Identity.GetUserId()))
            {
                return new HttpStatusCodeResult(HttpStatusCode.Unauthorized);
            }

            ViewBag.LocalID = new SelectList(db.Locals, "LocalID", "Name", pOI.LocalID);
            ViewBag.UserId = new SelectList(db.Users, "Id", "Email", pOI.UserId);
            return View(pOI);
        }

        // POST: POIs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrador")]
        public ActionResult Edit([Bind(Include = "POIID,Name,Description,LocalID,UserId,Validated")] POI pOI)
        {
            if (ModelState.IsValid)
            {
                POI poiTest = db.POIs.Find(pOI.POIID);
                if (poiTest.CheckNotOwner(User.Identity.GetUserId()))
                {
                    return new HttpStatusCodeResult(HttpStatusCode.Unauthorized);
                }
                db.Entry(poiTest).State = EntityState.Detached;

                pOI.UserId = User.Identity.GetUserId();
                db.Entry(pOI).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.LocalID = new SelectList(db.Locals, "LocalID", "Name", pOI.LocalID);
            ViewBag.UserId = new SelectList(db.Users, "Id", "Email", pOI.UserId);
            return View(pOI);
        }

        // GET: POIs/Delete/5
        [Authorize(Roles = "Administrador")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            POI pOI = db.POIs.Find(id);
            if (pOI == null)
            {
                return HttpNotFound();
            }
            
            return View(pOI);
        }

        // POST: POIs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrador")]
        public ActionResult DeleteConfirmed(int id)
        {
            POI pOI = db.POIs.Find(id);
            db.POIs.Remove(pOI);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        [Authorize(Roles = "Administrador")]
        public ActionResult IndexValidated()
        {
            var pOIs = db.POIs.Include(p => p.Local).Include(p => p.User);
            List<POI> validate = new List<POI>();
            foreach (POI poi in pOIs)
            {
                if (!poi.Validated)
                {
                    validate.Add(poi);
                }
            }
            return View(validate);
        }

        [Authorize(Roles ="Administrador")]
        public ActionResult Validate(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            POI pOI = db.POIs.Find(id);
            if (pOI == null)
            {
                return HttpNotFound();
            } else
            {
                pOI.Validated = true;
                db.SaveChanges();
            }

            return RedirectToAction("Index");
        }
    }
}

ARQSI/Lugares_Cancela_Visita/ARQSI_Projeto/Lugares/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Lugares</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Lugares", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Points of Interest", "Index", "POIs")</li>
                    <li>@Html.ActionLink("Locals", "Index", "Locals")</li>
                    <li>@Html.ActionLink("Hashtags", "Index", "Hashtags")</li>
                    <li>@Html.ActionLink("Visitas", "Index", "Visitas")</li>
                    <li>@Html.ActionLink("Validate POI", "IndexValidated","POIs")</li>

                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Lugares</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>